services:
  bedrock:
    build:
      context: ../../..
      dockerfile: detector/docker/bedrock/Dockerfile
    container_name: bedrock-container
    security_opt:
      - no-new-privileges:true
    environment:
      - AWS_PROFILE=default
      - AWS_REGION=${AWS_REGION}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_SHARED_CREDENTIALS_FILE=/home/sbx_user1051/.aws/credentials  # 追加
      - AWS_CONFIG_FILE=/home/sbx_user1051/.aws/config # 追加
    volumes:
      - ~/.aws/credentials:/home/sbx_user1051/.aws/credentials:ro
      - ~/.aws/config:/home/sbx_user1051/.aws/config:ro
    ports:
      - "9000:8080"
