services:
  edgkvsproducer:
    build:
      context: ../..
      dockerfile: test_movie/docker/Dockerfile
    security_opt:
      - no-new-privileges:true
    # .evn ファイルが必要です。以下の構成。もともとはisengardの自動更新で頑張ろうとしたものの、すぐタイムアウトしちゃうんんで、
    # 長期クレデンシャルをiam userで発行して使った方が楽です。
    # AWS_ACCESS_KEY_ID=<xxxxxxx>
    # AWS_SECRET_ACCESS_KEY=<xxxxxxx>
    env_file:
      - .env
    environment:
      - AWS_REGION=${AWS_REGION}
      - MOVIE_PATH=${MOVIE_PATH}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    ports:
      # RTSPサーバーポートをマッピング
      - "8554:8554"
    volumes:
      # ローカルのvideoディレクトリをコンテナにマウント
      - ./videos:/app/videos:ro
    # isengardの一時クレデンシャルを使いたいならこっち。けど、開発上はすぐにタイムアウトするのできつい。
    # volumes:
    #   - ~/.aws/credentials:/home/rtspuser/.aws/credentials:ro
    #   - ~/.aws/config:/home/rtspuser/.aws/config:ro
    # メモリ制限を追加（2.5GB動画処理用）
    # deploy:
    #   resources:
    #     limits:
    #       memory: 8G
    #     reservations:
    #       memory: 4G
